### ISSUE TITLE
screeny przełączanie i appbar jako kontener

### ISSUE THREAD

**Issue by matyjb** [matyjb/KampusSGGW2.0#11]
jak w tytule

**Comment by aglebionek2** [comment]
Czyli co, button lista ma po kliknięciu przechodzić na page "lista budynków", a button settings ma otwierać jakąś listę/panel gdzie będzie do wybrania "About" i dopiero stamtąd przejść na page about?

**Comment by matyjb** [comment]
Tak, ten button settings to taki dropdown

**Comment by aglebionek2** [comment]
Mogę zrobić Drawer po lewej, ale wtedy będę musiał zamienić widgeta HomePage ze Stateless na Stateful

**Comment by matyjb** [comment]
Nie, drawer się do tego nie nadaje.
Zrób nowy własny Widget w innym pliku, który będzie stateful i będzie miał jeden stan on/off.
 - jak jest 'on' to ten widget będzie miał w kolumnie: iconbutton ostawień, iconbutton about i tymczasowy iconbutton od motywu (jak na razie placeholder, więc nic nie robiący)
 - jak jest 'off' to pokazuje tylko iconbutton ustawień
No i ten własny widget do tego HomePage'a
----------------
p.s. Obstawiam, że tamten iconbutton po prawej będzie chciał być zawsze na wysokości środka tej kolumny po lewej, ale to można naprawić za pomocą crossAxisAlignment w widgecie Row (który jest tym appbarem)
