### ISSUE TITLE
floating action button wraz z subbuttonem

### ISSUE THREAD

**Issue by matyjb** [matyjb/KampusSGGW2.0#12]
tak jak tu: [koncept](https://www.figma.com/file/gpXFwh3MlsS2rWj00uIcWn/kampus-sggw)

**Comment by Sethreee** [comment]
Niestety nadal nie potrafię się posługiwać tym wszystkim, ale coś zrobiłam z tymi buttonami i się zastanawiam czy może być. Ogólnie czuję, że mam straszny bałagan w tym kodzie. Czy mogę wkleić tutaj ten kod i ktoś mógłby sprawdzić czy to co zrobiłam ma jakikolwiek sens? Ewentualnie jak to zrobić inaczej żebyście zobaczyli co napisałam?

**Comment by matyjb** [comment]
wystarczy, ze zrobisz commit i potem push

**Comment by matyjb** [comment]
Nie no spoko ci wyszło, nawet fajnie, że temu mniejszemu guzikowi dałaś kolory odwrotnie niż w koncepcie ale nawet ładniej tak jest. 
Tam trochę uporządkowałem, bo trochę za sztywno się kierowaliście tym konceptem gdzie nie patrzyłem na skale tych guzików i nie potrzebnie skalowaliście ikony itp.
Już to zmerguje w masterem (i jak znajdę taska to może ci przydzielę)
