### ISSUE TITLE
ikona/marker/pinezka budynku

### ISSUE THREAD

**Issue by matyjb** [matyjb/KampusSGGW2.0#6]
ikona powinna być szablonowa by można było na nią nanieść np. numer budynku

**Comment by 4Maksio** [comment]
Mam kilka propozycji - szkicy w 2D, jak trzeba to na 3D zmienię, tylko co będzie najlepsze i w jakich kolorach?

**Comment by matyjb** [comment]
2d będą lepsze, a kolory to trzymajmy się koloru zielonego jako koloru przewodniego

**Comment by 4Maksio** [comment]
To pozostaje, które, lub połączenie których z zaproponowanych, miałoby być tym właściwym pinem i jaka ma być ostateczny rozmiar?

**Comment by matyjb** [comment]
Zobaczyłem co tam zrobiłeś i zdecydowanie polecałbym Ci nabranie inspiracji z google'a czy innego źródła jak takie piny wyglądają (możesz wziąć jakiś z internetu i przerobić)
O rozmiar się nie martw.

**Comment by 4Maksio** [comment]
Chciałem być kreatywny...

**Comment by 4Maksio** [comment]
Myślę, że teraz jest już lepiej.
